config/routes.rb
MyGists3::Application.routes.draw do
  resources :gists

  root 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.paginate(page: params[:page], per_page: 7).order('created_at DESC')
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>

  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
    <td> <%= f.label :"Kod programu" %></td>
    <td><%= f.label :"Opis programu" %></td>
</tr>
<tr>
  <td><%= f.text_area :snippet, :class => "area_kod" %></td>
      <td><%= f.text_area :description, :class => "area_opis" %></td>
  </tr>
  <tr><div class="field">
    <td align="right"><%= f.label :Jezyk %></td>
    <td><%= f.text_field :lang %></td>
    </div>
    </tr>
    <tr><td></td><td align="center">
<div class="actions">
    <%= f.submit :"Akceptuj"%>
  </div></td></tr>
  </table>
<% end %>

app/views/gists/edit.html.erb
<h1>Editing gist</h1>

<div class="center hero-unit">
<%= render 'form' %>
<center>
<button type="button" class="btn btn-default btn-large"><%= link_to 'Pokaż', @gist %></button> 
<button type="button" class="btn btn-default btn-large"><%= link_to 'Wróć', gists_path %></button>
</center>
</div>

app/views/gists/index.html.erb
<div class="navbar navbar-default navbar-fixed-top">
<div class="navbar-inner">
<h1>Umieszczanie gistów</h1></div></div>
<div class="center hero-unit">
<table border="1">
  <thead>
    <tr bgcolor="#DDDDDD">
      <th><font color="blue">Snippet</font></th>
      <th><font color="blue">Lang</font></th>
      <th><font color="blue">Description</font></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
<div class="table">
  <tbody bgcolor="#99FFCC">
    <% @gists.each do |gist| %>
    <div class="display">
      <tr>
        <td><%= raw Pygments.highlight(gist.snippet.length > 30 ? gist.snippet[0,90] + "" : gist.snippet, lexer: gist.lang) %></td>
        <td align="center" width="100"><b><%= gist.lang %></b></td>
        <td width="150"><%= gist.description %></td>
        <td width="75" align="center"><button type="button" class="btn btn-default"><%= link_to 'Pokaż', gist %></button></td>
        <td width="75" align="center"><button type="button" class="btn btn-default"><%= link_to 'Edytuj', edit_gist_path(gist) %></button></td>
        <td width="75" align="center"><button type="button" class="btn btn-default"><%= link_to 'Usuń', gist, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr></div>
    <% end %>
  </tbody>
  </div>
</table>
<br />
<center><button type="button" class="btn btn-default btn-large"><%= link_to 'Dodaj', new_gist_path %></button></center>
<center><%= will_paginate %></center>
</div>

app/views/gists/new.html.erb
<div class="navbar navbar-default navbar-fixed-top">
<div class="navbar-inner"><h1>Nowy gist</h1></div>
</div>

<div class="center hero-unit">
<%= render 'form' %>
<hr />
<center><button type="button" class="btn btn-large btn-default "><%= link_to 'Cofnij', gists_path %></button></center>
</div>

app/views/gists/show.html.erb
<h1>Treść Twojego GISTA</h1>
<div class="center hero-unit">
<p id="notice"><%= notice %></p>
<p class="navbar-text">
  <strong>Lang:</strong>
  <%= @gist.lang %>
</p>
<p class="navbar-text">
  <strong>Description:</strong>
  <%= @gist.description %>
</p>
<p class="navbar-text">
  <strong>Snippet:</strong>
</p>
<%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
<p align="center"><button type="button" class="btn btn-default btn-large"><%= link_to 'Edytuj', edit_gist_path(@gist) %></button> 
<button type="button" class="btn btn-default btn-large"><%= link_to 'Wróć', gists_path %></button>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGists3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>